language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - docker

jobs:
  include:
    - script:
        - mvn clean spring-boot:build-image

      name: "Build Spring Boot app with build-image Maven plugin"

    - script:
        # Install pack CLI via homebrew. See https://buildpacks.io/docs/tools/pack/#pack-cli
        - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

        # Build app with pack CLI
        - pack build spring-boot-buildpack --path . --builder paketobuildpacks/builder:base

        # Push to Docker Hub also
        - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag spring-boot-buildpack jonashackt/spring-boot-buildpack:latest
        - docker push jonashackt/spring-boot-buildpack:latest

      name: "Build Spring Boot app with Paketo.io pack CLI"

