name: build

on: [push]

jobs:
  build-with-maven-push-2-ghcr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Show Docker info
        run: |
          docker info
          sudo ls -la /var/lib/docker

      - name: Login to GitHub Container Registry
        run: echo $CR_PAT | docker login ghcr.io -u jonashackt --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
        run: mvn spring-boot:build-image --batch-mode --no-transfer-progress

      - name: Tag Paketo build image to have the right GitHub Container Registry coordinates
        run:  docker tag spring-boot-buildpack:0.0.1-SNAPSHOT ghcr.io/jonashackt/spring-boot-buildpack:latest

      - name: Push the image to GitHub Container Registry
        run:  docker push ghcr.io/jonashackt/spring-boot-buildpack:latest

  build-with-paketo-push-2-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Paketo CLI and publish to Docker Hub
        run: |
          echo 'Login to DockerHub Container Registry'
          echo $DOCKER_HUB_TOKEN | docker login -u jonashackt --password-stdin

          echo 'Install pack CLI via apt. See https://buildpacks.io/docs/tools/pack/#pack-cli'
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

          echo 'Build app with pack CLI'
          pack build spring-boot-buildpack --path . --builder paketobuildpacks/builder:base

          echo 'Push to Docker Hub'
          docker tag spring-boot-buildpack jonashackt/spring-boot-buildpack:latest
          docker push jonashackt/spring-boot-buildpack:latest
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}